#!/bin/bash

echo enter 1 to open vim
echo enter 2 to open nano
echo enter 3 to show information about current java version
echo enter 4 to exit

while true ; do
read number
case $number in 
1 )
vim "$@"
;;
2 )
nano "$@"
;;
3 )
java "$@"
;;
4 )
break
;;
esac
done

